services:
  - type: web
    name: healthcare-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: False
